# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Ddabong2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ddabong2

  pod 'MessageKit'  
 post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'  
      end
    end
  end
  target 'Ddabong2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Ddabong2UITests' do
    # Pods for testing
  end

end
