# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Ddabong2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ddabong2

  target 'Ddabong2Tests' do
    # Pods for testing
  end

  target 'Ddabong2UITests' do
    # Pods for testing
  end

end
